### ISSUE TITLE
Error on start up

### ISSUE THREAD

**Issue by larssieboy18** [hypersmc/WebServerPlugin#1]
Hi there,

Whenever I start the plugin, I get the following error (https://mcpaste.io/053c384f445a9976):

`[18:28:54 ERROR]: Error occurred while enabling WebPlugin v0.9 (Is it up to date?)
java.lang.IllegalArgumentException: The embedded resource 'ssl/removeme.txt' cannot be found in plugins/WebServerPlugin-0.9.jar
        at org.bukkit.plugin.java.JavaPlugin.saveResource(JavaPlugin.java:192) ~[patched_1.16.4.jar:git-Tuinity-"4743c34"]
        at me.hypersmc.jumpwatch.humpjump.webserver.Main.onEnable(Main.java:137) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Tuinity-"4743c34"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Tuinity-"4743c34"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Tuinity-"4743c34"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Tuinity-"4743c34"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Tuinity-"4743c34"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:465) ~[patched_1.16.4.jar:git-Tuinity-"4743c34"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:240) ~[patched_1.16.4.jar:git-Tuinity-"4743c34"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:933) ~[patched_1.16.4.jar:git-Tuinity-"4743c34"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.4.jar:git-Tuinity-"4743c34"]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[18:28:54 INFO]: [WebPlugin] Disabling WebPlugin v0.9
[18:28:55 WARN]: java.net.ConnectException: Connection refused (Connection refused)
[18:28:55 WARN]:        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
[18:28:55 WARN]:        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
[18:28:55 WARN]:        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
[18:28:55 WARN]:        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
[18:28:55 WARN]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
[18:28:55 WARN]:        at java.base/java.net.Socket.connect(Socket.java:609)
[18:28:55 WARN]:        at java.base/java.net.Socket.connect(Socket.java:558)
[18:28:55 WARN]:        at java.base/java.net.Socket.<init>(Socket.java:454)
[18:28:55 WARN]:        at java.base/java.net.Socket.<init>(Socket.java:231)
[18:28:55 WARN]:        at me.hypersmc.jumpwatch.humpjump.webserver.Main.onDisable(Main.java:203)
[18:28:55 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[18:28:55 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415)
[18:28:55 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516)
[18:28:55 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384)
[18:28:55 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[18:28:55 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[18:28:55 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[18:28:55 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:465)
[18:28:55 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:240)
[18:28:55 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:933)
[18:28:55 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174)
[18:28:55 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[18:28:55 ERROR]: Error occurred while disabling WebPlugin v0.9 (Is it up to date?)
java.lang.NullPointerException: null
        at me.hypersmc.jumpwatch.humpjump.webserver.Main.onDisable(Main.java:213) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.4.jar:git-Tuinity-"4743c34"]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.4.jar:git-Tuinity-"4743c34"]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.4.jar:git-Tuinity-"4743c34"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.4.jar:git-Tuinity-"4743c34"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Tuinity-"4743c34"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Tuinity-"4743c34"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Tuinity-"4743c34"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:465) ~[patched_1.16.4.jar:git-Tuinity-"4743c34"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:240) ~[patched_1.16.4.jar:git-Tuinity-"4743c34"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:933) ~[patched_1.16.4.jar:git-Tuinity-"4743c34"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.4.jar:git-Tuinity-"4743c34"]
        at java.lang.Thread.run(Thread.java:834) [?:?]`

Is there any way to resolve it? The ports have been configured correctly and are open.

**Comment by hypersmc** [comment]
Hello @larssieboy18,

This seems to be a very easy fix as ssl folder wasn't found in the plugin.
This issue is fixed in 0.9.17

Thanks for bringing it up to me!

**Comment by hypersmc** [comment]
Issue seems still to exist... Looking further into it.
